import { GradeTemplate } from "./types";

export const PRESET_IMAGES = [
  {
    id: "autumn_leaf",
    name: "🍁 Mùa Thu Sinh Động Hữu Tình",
    url: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?q=80&w=1200&auto=format&fit=crop",
    color: "#ea580c"
  },
  {
    id: "snake_2025",
    name: "🌸 Tết Ất Tỵ 2025 (Hoa Đào Xuân)",
    url: "https://images.unsplash.com/photo-1522383225653-ed111181a951?q=80&w=1200&auto=format&fit=crop",
    color: "#15803d"
  },
  {
    id: "womens_day_8_3",
    name: "💖 Quốc tế Phụ nữ 8/3 (Hồng Hoa)",
    url: "https://images.unsplash.com/photo-1526047932273-341f2a7631f9?q=80&w=1200&auto=format&fit=crop",
    color: "#db2777"
  },
  {
    id: "school_achievement",
    name: "🧪 Khoa Học Kỳ Diệu (Vật Lý Hóa Học)",
    url: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?q=80&w=1200&auto=format&fit=crop",
    color: "#1e3a8a"
  }
];

export const GRADE_TEMPLATES: GradeTemplate[] = [
  {
    grade: 10,
    subject: "Hóa Học 10",
    topics: [
      {
        id: "10_atomic",
        title: "Chương 1. Cấu tạo nguyên tử",
        description: "Khám phá thành phần hạt nhân, lớp và phân lớp electron, cùng orbital nguyên tử (AO).",
        iconName: "Atom",
        color: "#1e3a8a",
        data: [
          { "question": "Hạt mang điện tích dương nằm trong hạt nhân nguyên tử gọi là gì?", "answer": "Proton" },
          { "question": "Vỏ nguyên tử được cấu tạo bởi các hạt nào mang điện tích âm?", "answer": "Electron" },
          { "question": "Hạt không mang điện nằm trong hạt nhân nguyên tử gọi là gì?", "answer": "Neutron" },
          { "question": "Số khối của hạt nhân (A) được tính bằng tổng số hạt nào?", "answer": "Proton và Neutron" },
          { "question": "Các nguyên tử có cùng số hiệu nguyên tử nhưng khác nhau về số neutron gọi là gì?", "answer": "Đồng vị" },
          { "question": "Vùng không gian xung quanh hạt nhân có xác suất tìm thấy electron lớn nhất là gì?", "answer": "Orbital nguyên tử (AO)" },
          { "question": "Số lượng electron tối đa có thể chứa trong một orbital nguyên tử là?", "answer": "2 electron" },
          { "question": "Phân lớp electron s chứa tối đa bao nhiêu electron?", "answer": "2 electron" },
          { "question": "Phân lớp electron p chứa tối đa bao nhiêu electron?", "answer": "6 electron" },
          { "question": "Phân lớp electron d chứa tối đa bao nhiêu electron?", "answer": "10 electron" },
          { "question": "Phân lớp electron f chứa tối đa bao nhiêu electron?", "answer": "14 electron" },
          { "question": "Lớp electron ngoài cùng quyết định tính chất hóa học nào của nguyên tố?", "answer": "Tính kim loại, phi kim hoặc khí hiếm" },
          { "question": "Cấu hình electron lớp ngoài cùng dạng \\(ns^2 np^5\\) là của nhóm nguyên tố nào?", "answer": "Halogen (Nhóm VIIA)" },
          { "question": "Nguyên tố có cấu hình electron lớp ngoài cùng là \\(3s^1\\) thuộc chu kỳ mấy?", "answer": "Chu kỳ 3" },
          { "question": "Vỏ của nguyên tử helium (He, Z=2) có bao nhiêu electron?", "answer": "2 electron" },
          { "question": "Số phân lớp electron có trong lớp electron thứ 3 (lớp M) là bao nhiêu?", "answer": "3 phân lớp" },
          { "question": "Ký hiệu phân lớp nào sau đây không thể tồn tại trong lớp vỏ nguyên tử?", "answer": "1p" },
          { "question": "Các phân lớp electron đã đầy hoặc đạt tối đa số electron gọi là phân lớp gì?", "answer": "Phân lớp bão hòa" },
          { "question": "Nguyên tố sodium có Z = 11 có cấu hình electron viết gọn là gì?", "answer": "\\([Ne] 3s^1\\)" },
          { "question": "Quy tắc phân bố electron vào các orbital sao cho số electron độc thân là tối đa gọi là?", "answer": "Quy tắc Hund" }
        ]
      },
      {
        id: "10_periodic",
        title: "Chương 2. Bảng tuần hoàn & Định luật tuần hoàn",
        description: "Chu kỳ, nhóm, định luật tuần hoàn và quy luật biến đổi bán kính, tính kim loại phi kim.",
        iconName: "Layers",
        color: "#0f766e",
        data: [
          { "question": "Các nguyên tố trong bảng tuần hoàn được sắp xếp theo chiều tăng dần của?", "answer": "Điện tích hạt nhân" },
          { "question": "Các nguyên tố có cùng số lớp electron trong nguyên tử được xếp vào cùng một?", "answer": "Chu kỳ" },
          { "question": "Các nguyên tố có tính chất tương tự nhau và cùng số electron hóa trị được xếp vào cùng một?", "answer": "Nhóm" },
          { "question": "Bảng tuần hoàn các nguyên tố hóa học hiện nay gồm bao nhiêu chu kỳ?", "answer": "7 chu kỳ" },
          { "question": "Chu kỳ nhỏ nhất trong bảng tuần hoàn chỉ chứa 2 nguyên tố là chu kỳ mấy?", "answer": "Chu kỳ 1" },
          { "question": "Theo chiều tăng dần của điện tích hạt nhân trong một chu kỳ, bán kính nguyên tử sẽ?", "answer": "Giảm dần" },
          { "question": "Đại lượng đặc trưng cho khả năng hút electron khi tạo liên kết của nguyên tử là gì?", "answer": "Độ âm điện" },
          { "question": "Trong một nhóm A, đi từ trên xuống dưới, tính phi kim của các nguyên tố sẽ?", "answer": "Giảm dần" },
          { "question": "Trong một nhóm A, đi từ trên xuống dưới, tính kim loại của các nguyên tố sẽ?", "answer": "Tăng dần" },
          { "question": "Nguyên tố phi kim có độ âm điện lớn nhất trong bảng tuần hoàn là nguyên tố nào?", "answer": "Fluorine (F)" },
          { "question": "Oxide cao nhất của một nguyên tố nhóm IVA có công thức chung là gì?", "answer": "\\(RO_2\\)" },
          { "question": "Kim loại kiềm thuộc nhóm nào trong bảng tuần hoàn?", "answer": "Nhóm IA" },
          { "question": "Kim loại kiềm thổ thuộc nhóm nào trong bảng tuần hoàn?", "answer": "Nhóm IIA" },
          { "question": "Nhóm nguyên tố có cấu hình electron lớp ngoài cùng bền vững dạng \\(ns^2 np^6\\) là nhóm gì?", "answer": "Khí hiếm" },
          { "question": "Theo chiều tăng điện tích hạt nhân trong một chu kỳ, tính acid của các oxide cao nhất sẽ?", "answer": "Tăng dần" },
          { "question": "Theo chiều tăng điện tích hạt nhân trong một chu kỳ, tính base của các hydroxide tương ứng sẽ?", "answer": "Giảm dần" },
          { "question": "Nguyên tố phi kim mạnh nhất trong bảng tuần hoàn thuộc nhóm nào?", "answer": "Nhóm VIIA" },
          { "question": "Kim loại mạnh nhất trong bảng tuần hoàn (không tính nguyên tố phóng xạ) là gì?", "answer": "Cesium (Cs)" },
          { "question": "Chu kỳ 4 trong bảng tuần hoàn bắt đầu bằng kim loại kiềm nào?", "answer": "Potassium (K)" },
          { "question": "Số thứ tự của nhóm A trong bảng tuần hoàn bằng số lượng electron nào ở lớp ngoài cùng?", "answer": "Electron hóa trị" }
        ]
      },
      {
        id: "10_bonding",
        title: "Chương 3. Liên kết hóa học",
        description: "Quy tắc octet, liên kết ion, liên kết cộng hóa trị, liên kết hydrogen và tương tác van der Waals.",
        iconName: "Sparkles",
        color: "#701a75",
        data: [
          { "question": "Quy tắc octet phát biểu rằng các nguyên tử xu hướng đạt cấu hình bền vững lớp ngoài cùng của?", "answer": "Khí hiếm" },
          { "question": "Liên kết được hình thành do lực hút tĩnh điện giữa các ion trái dấu gọi là liên kết gì?", "answer": "Liên kết ion" },
          { "question": "Liên kết được tạo thành bởi một hoặc nhiều cặp electron dùng chung giữa hai nguyên tử gọi là?", "answer": "Liên kết cộng hóa trị" },
          { "question": "Hiệu độ âm điện giữa hai nguyên tử lớn hơn hoặc bằng 1,7 thì liên kết là loại gì?", "answer": "Liên kết ion" },
          { "question": "Hiệu độ âm điện từ 0,4 đến dưới 1,7 thì liên kết là liên kết cộng hóa trị dạng nào?", "answer": "Cộng hóa trị phân cực" },
          { "question": "Liên kết được hình thành do sự xen phủ trục dọc của các orbital gọi là liên kết gì?", "answer": "Liên kết sigma" },
          { "question": "Liên kết được hình thành do sự xen phủ bên của các orbital gọi là liên kết gì?", "answer": "Liên kết pi" },
          { "question": "Liên kết yếu hình thành giữa nguyên tử H phân cực dương với nguyên tử có độ âm điện lớn còn electron tự do là?", "answer": "Liên kết hydrogen" },
          { "question": "Lực tương tác tĩnh điện yếu giữa các phân tử phân cực tạm thời được gọi là tương tác gì?", "answer": "Tương tác van der Waals" },
          { "question": "Nhờ có liên kết hydrogen liên phân tử mạnh mẽ, nước (\\(H_2O\\)) có tính chất vật lý đặc biệt nào?", "answer": "Nhiệt độ sôi cao bất thường" },
          { "question": "Hợp chất chứa liên kết ion thường có trạng thái vật lý nào ở nhiệt độ thường?", "answer": "Chất rắn kết tinh" },
          { "question": "Phân tử khí nitrogen (\\(N_2\\)) có liên kết hóa học bền vững thuộc loại liên kết gì?", "answer": "Liên kết ba" },
          { "question": "Liên kết cộng hóa trị trong đó cặp electron dùng chung chỉ do một nguyên tử đóng góp gọi là?", "answer": "Liên kết cho - nhận" },
          { "question": "Phân tử nước (\\(H_2O\\)) có dạng hình học phân tử là hình gì?", "answer": "Hình chữ V" },
          { "question": "Phân tử carbon dioxide (\\(CO_2\\)) có cấu trúc hình học phân tử là hình gì?", "answer": "Thẳng hàng" },
          { "question": "Sự tương tác van der Waals làm tăng nhiệt độ sôi của các khí hiếm từ trên xuống do yếu tố nào?", "answer": "Khối lượng phân tử tăng" },
          { "question": "Khi tạo liên kết cộng hóa trị phân cực, cặp electron dùng chung lệch về phía nguyên tử có độ âm điện thế nào?", "answer": "Độ âm điện lớn hơn" },
          { "question": "Các chất có liên kết cộng hóa trị không phân cực thường tan tốt trong loại dung môi nào?", "answer": "Dung môi không phân cực" },
          { "question": "Tinh table kim cương có cấu trúc mạng tinh thể thuộc loại nào cực kỳ bền cứng?", "answer": "Mạng tinh thể nguyên tử" },
          { "question": "Mạng tinh thể của nước đá ở trạng thái đóng băng thuộc loại tinh thể nào?", "answer": "Tinh thể phân tử" }
        ]
      },
      {
        id: "10_redox",
        title: "Chương 4. Phản ứng oxi hóa - khử",
        description: "Phương pháp thăng bằng electron, xác định số oxi hóa, vai trò chất khử và chất oxi hóa.",
        iconName: "Zap",
        color: "#b45309",
        data: [
          { "question": "Trong phản ứng oxi hóa - khử, chất nhường electron được gọi là chất gì?", "answer": "Chất khử" },
          { "question": "Quá trình nhận electron của một chất được gọi là quá trình gì?", "answer": "Quá trình khử" },
          { "question": "Số oxi hóa của hydrogen trong hầu hết các hợp chất hóa học là bao nhiêu?", "answer": "+1" },
          { "question": "Số oxi hóa của oxygen trong hầu hết các hợp chất hóa học là bao nhiêu?", "answer": "-2" },
          { "question": "Số oxi hóa của một đơn chất ở trạng thái tự do luôn bằng bao nhiêu?", "answer": "0" },
          { "question": "Trong một phân tử trung hòa, tổng số oxi hóa của các nguyên tố bằng bao nhiêu?", "answer": "0" },
          { "question": "Trong phản ứng oxi hóa - khử, chất đóng vai trò nhận electron là chất gì?", "answer": "Chất oxi hóa" },
          { "question": "Sự tăng số oxi hóa của một chất sau phản ứng ứng với quá trình gì?", "answer": "Quá trình oxi hóa" },
          { "question": "Sự giảm số oxi hóa của một chất sau phản ứng ứng với quá trình gì?", "answer": "Quá trình khử" },
          { "question": "Số oxi hóa của kim loại kiềm trong các hợp chất luôn bằng bao nhiêu?", "answer": "+1" },
          { "question": "Số oxi hóa của kim loại kiềm thổ trong các hợp chất luôn bằng bao nhiêu?", "answer": "+2" },
          { "question": "Trong hợp chất \\(Al_2O_3\\), số oxi hóa của aluminium (Al) là bao nhiêu?", "answer": "+3" },
          { "question": "Số oxi hóa của nitrogen trong ion amoni (\\(NH_4^+\\)) là bao nhiêu?", "answer": "-3" },
          { "question": "Phản ứng nào sau đây luôn là phản ứng oxi hóa - khử?", "answer": "Phản ứng thế" },
          { "question": "Số oxi hóa của lưu huỳnh (S) trong hợp chất \\(H_2SO_4\\) là bao nhiêu?", "answer": "+6" },
          { "question": "Số oxi hóa của chlorine trong hợp chất \\(KClO_3\\) là bao nhiêu?", "answer": "+5" },
          { "question": "Trong phản ứng: \\(3Cl_2 + 6KOH \\rightarrow 5KCl + KClO_3 + 3H_2O\\), chlorine đóng vai trò gì?", "answer": "Vừa là chất oxi hóa, vừa là chất khử" },
          { "question": "Phản ứng tự oxi hóa - tự khử là phản ứng mà một nguyên tố đóng vai trò thế nào?", "answer": "Vừa nhường vừa nhận electron" },
          { "question": "Phương pháp cân bằng phản ứng oxi hóa - khử dựa trên nguyên tắc bảo toàn electron gọi là gì?", "answer": "Phương pháp thăng bằng electron" },
          { "question": "Trong phản ứng của sodium với khí chlorine, hạt nào đã nhường electron?", "answer": "Nguyên tử sodium (Na)" }
        ]
      },
      {
        id: "10_thermo",
        title: "Chương 5. Năng lượng hóa học",
        description: "Phản ứng tỏa nhiệt, thu nhiệt, biến thiên enthalpy chuẩn và nhiệt tạo thành chuẩn.",
        iconName: "Zap",
        color: "#be185d",
        data: [
          { "question": "Phản ứng giải phóng năng lượng dưới dạng nhiệt ra môi trường xung quanh gọi là gì?", "answer": "Phản ứng tỏa nhiệt" },
          { "question": "Phản ứng hấp thu năng lượng dưới dạng nhiệt từ môi trường xung quanh gọi là gì?", "answer": "Phản ứng thu nhiệt" },
          { "question": "Biến thiên enthalpy chuẩn (\\(\\Delta_r H^o_{298}\\)) nhỏ hơn 0 tương ứng với phản ứng loại gì?", "answer": "Phản ứng tỏa nhiệt" },
          { "question": "Biến thiên enthalpy chuẩn (\\(\\Delta_r H^o_{298}\\)) lớn hơn 0 tương ứng với phản ứng loại gì?", "answer": "Phản ứng thu nhiệt" },
          { "question": "Ký hiệu đặc trưng cho nhiệt tạo thành chuẩn của một chất hóa học là gì?", "answer": "\\(\\Delta_f H^o_{298}\\)" },
          { "question": "Điều kiện chuẩn về nhiệt độ trong nhiệt hóa học tương ứng với bao nhiêu độ C?", "answer": "25 độ C" },
          { "question": "Phản ứng đốt cháy các loại nhiên liệu hóa thạch luôn thuộc loại phản ứng nhiệt động nào?", "answer": "Phản ứng tỏa nhiệt" },
          { "question": "Nhiệt lượng tỏa ra hay thu vào của phản ứng ở áp suất không đổi gọi là gì?", "answer": "Biến thiên enthalpy" },
          { "question": "Biến thiên enthalpy chuẩn được xác định ở mức áp suất chuẩn bằng bao nhiêu bar?", "answer": "1 bar" },
          { "question": "Nhiệt tạo thành chuẩn của các đơn chất bền vững nhất ở điều kiện chuẩn bằng bao nhiêu?", "answer": "0" },
          { "question": "Quá trình quang hợp của cây xanh hấp thụ ánh sáng mặt trời thuộc loại phản ứng nào?", "answer": "Phản ứng thu nhiệt" },
          { "question": "Thiết bị dùng để đo lượng nhiệt tỏa ra hoặc thu vào trong phản ứng hóa học gọi là gì?", "answer": "Nhiệt lượng kế" },
          { "question": "Phương trình hóa học ghi kèm giá trị biến thiên enthalpy và trạng thái các chất gọi là?", "answer": "Phương trình nhiệt hóa học" },
          { "question": "Phản ứng phân hủy đá vôi \\(CaCO_3\\) thành CaO và \\(CO_2\\) ở nhiệt độ cao là phản ứng tỏa hay thu nhiệt?", "answer": "Phản ứng thu nhiệt" },
          { "question": "Sự hòa tan muối ăn (NaCl) vào nước là một quá trình thu nhiệt nhẹ, nhiệt độ dung dịch sẽ?", "answer": "Giảm đi" },
          { "question": "Khi đun nóng bếp gas, năng lượng từ phản ứng đốt cháy butane được giải phóng dưới dạng nào?", "answer": "Nhiệt năng" },
          { "question": "Công thức tính biến thiên enthalpy phản ứng dựa vào nhiệt tạo thành chuẩn là gì?", "answer": "Tổng nhiệt tạo thành sản phẩm trừ chất đầu" },
          { "question": "Nhiệt lượng tỏa ra hoặc thu vào khi tạo thành 1 mol chất từ các đơn chất bền vững ở điều kiện chuẩn gọi là gì?", "answer": "Nhiệt tạo thành chuẩn" },
          { "question": "Đơn vị thông dụng để đo nhiệt lượng và biến thiên enthalpy trong hóa học là gì?", "answer": "kJ hoặc kcal" },
          { "question": "Phản ứng trung hòa giữa acid mạnh và base mạnh trong nước luôn là phản ứng tỏa hay thu nhiệt?", "answer": "Phản ứng tỏa nhiệt" }
        ]
      },
      {
        id: "10_kinetics",
        title: "Chương 6. Tốc độ phản ứng",
        description: "Các yếu tố ảnh hưởng nồng độ, nhiệt độ, áp suất, diện tích tiếp xúc và chất xúc tác.",
        iconName: "Compass",
        color: "#0369a1",
        data: [
          { "question": "Đại lượng đặc trưng cho mức độ nhanh hay chậm của một phản ứng hóa học gọi là gì?", "answer": "Tốc độ phản ứng" },
          { "question": "Tốc độ phản ứng được đo bằng sự thay đổi của đại lượng nào trong một đơn vị thời gian?", "answer": "Nồng độ của chất phản ứng hoặc sản phẩm" },
          { "question": "Khi tăng nồng độ các chất phản ứng, tốc độ phản ứng nói chung sẽ thay đổi thế nào?", "answer": "Tăng lên" },
          { "question": "Khi tăng áp suất đối với các phản ứng có chất khí tham gia, tốc độ phản ứng sẽ?", "answer": "Tăng lên" },
          { "question": "Yếu tố diện tích bề mặt tiếp xúc chỉ ảnh hưởng đến tốc độ của phản ứng thuộc loại nào?", "answer": "Phản ứng dị thể (giữa các pha khác nhau)" },
          { "question": "Nghiền nhỏ một chất rắn trước khi cho tham gia phản ứng nhằm mục đích gì?", "answer": "Tăng diện tích bề mặt tiếp xúc" },
          { "question": "Khi tăng nhiệt độ lên khoảng 10 độ C, tốc độ phản ứng thường tăng từ 2 đến 4 lần. Quy luật này gọi là?", "answer": "Quy tắc Van't Hoff" },
          { "question": "Hệ số nhiệt độ Van't Hoff kí hiệu là chữ cái gì?", "answer": "\\(\\gamma\\) (Gamma)" },
          { "question": "Chất làm tăng tốc độ phản ứng nhưng không bị biến đổi về lượng và chất sau phản ứng gọi là gì?", "answer": "Chất xúc tác" },
          { "question": "Các chất xúc tác sinh học hoạt động trong cơ thể sinh vật có tên gọi chung là gì?", "answer": "Enzyme" },
          { "question": "Để bảo quản thực phẩm được lâu hơn, người ta thường để trong tủ lạnh. Yếu tố tốc độ nào được áp dụng ở đây?", "answer": "Giảm nhiệt độ" },
          { "question": "Quạt lò than để than cháy nhanh hơn là ứng dụng việc tăng nồng độ của khí nào?", "answer": "Khí oxygen (trong không khí)" },
          { "question": "Chất xúc tác làm tăng tốc độ phản ứng bằng cách làm giảm đại lượng nào của phản ứng?", "answer": "Năng lượng hoạt hóa" },
          { "question": "Nhiên liệu được sản xuất dưới dạng viên than tổ ong có nhiều lỗ rỗng nhằm mục đích gì?", "answer": "Tăng diện tích tiếp xúc với không khí" },
          { "question": "Tốc độ phản ứng tại một thời điểm xác định được gọi là loại tốc độ nào?", "answer": "Tốc độ tức thời" },
          { "question": "Để dập tắt đám cháy nhỏ bằng bình chữa cháy \\(CO_2\\), người ta ngăn cản sự tiếp xúc của chất cháy với chất nào?", "answer": "Khí oxygen" },
          { "question": "Khi tăng nhiệt độ, các phân tử chuyển động nhanh hơn, dẫn đến tăng số lượng yếu tố nào giữa chúng?", "answer": "Va chạm hiệu quả" },
          { "question": "Chất xúc tác có mặt trong cùng một pha với các chất phản ứng gọi là xúc tác gì?", "answer": "Xúc tác đồng thể" },
          { "question": "Thiết bị chuyển đổi khí thải ở ống xả ô tô chứa các kim loại quý (Pt, Pd) đóng vai trò gì?", "answer": "Chất xúc tác dị thể" },
          { "question": "Sự giảm nồng độ chất phản ứng theo thời gian tỷ lệ thế nào với sự tăng nồng độ sản phẩm?", "answer": "Tỷ lệ thuận theo hệ số tỷ lượng" }
        ]
      },
      {
        id: "10_halogen",
        title: "Chương 7. Nguyên tố nhóm halogen",
        description: "Tính chất phi kim mạnh của nhóm Halogen, hydrogen halide và ứng dụng khử trùng tẩy trắng.",
        iconName: "FlaskConical",
        color: "#15803d",
        data: [
          { "question": "Nhóm Halogen nằm ở nhóm mấy A trong bảng tuần hoàn các nguyên tố hóa học?", "answer": "Nhóm VIIA" },
          { "question": "Kể tên 4 nguyên tố nhóm Halogen phổ biến theo chiều tăng dần số hiệu nguyên tử?", "answer": "Fluorine, Chlorine, Bromine, Iodine" },
          { "question": "Đơn chất halogen nào ở điều kiện thường tồn tại ở trạng thái lỏng, màu đỏ nâu?", "answer": "Bromine (\\(Br_2\\))" },
          { "question": "Đơn chất halogen nào ở điều kiện thường là chất rắn màu tím đen, dễ bị thăng hoa khi đun nóng?", "answer": "Iodine (\\(I_2\\))" },
          { "question": "Đơn chất halogen nào là chất khí màu vàng lục, mùi xốc và rất độc?", "answer": "Chlorine (\\(Cl_2\\))" },
          { "question": "Các halogen có cấu hình electron lớp ngoài cùng dạng tổng quát như thế nào?", "answer": "\\(ns^2 np^5\\)" },
          { "question": "Theo chiều từ fluorine đến iodine, độ âm điện của các halogen thay đổi thế nào?", "answer": "Giảm dần" },
          { "question": "Halogen nào có tính phi kim và tính oxi hóa mạnh nhất trong nhóm?", "answer": "Fluorine (F)" },
          { "question": "Dung dịch nước của khí hydrogen chloride (HCl) có tên gọi là gì?", "answer": "Hydrochemical acid (Axit clohiđric)" },
          { "question": "Dung dịch axit halogenhydric nào sau đây có tính axit mạnh nhất?", "answer": "Hydroiodic acid (HI)" },
          { "question": "Chất nào được dùng để nhận biết hồ tinh bột bằng hiện tượng hóa xanh đặc trưng?", "answer": "Iodine (\\(I_2\\))" },
          { "question": "Thuốc thử đặc trưng dùng để nhận biết các ion halogenua (\\(Cl^-\\), \\(Br^-\\), \\(I^-\\)) là dung dịch muối nào?", "answer": "Silver nitrate (\\(AgNO_3\\))" },
          { "question": "Khi nhỏ dung dịch \\(AgNO_3\\) vào dung dịch muối NaCl, xuất hiện kết tủa màu gì?", "answer": "Màu trắng" },
          { "question": "Kết tủa Silver bromide (\\(AgBr\\)) có màu gì đặc trưng?", "answer": "Màu vàng nhạt" },
          { "question": "Kết tủa Silver iodide (\\(AgI\\)) có màu gì đặc trưng?", "answer": "Màu vàng đậm" },
          { "question": "Hỗn hợp khí chlorine và dung dịch NaOH ở nhiệt độ thường tạo ra nước tẩy rửa gì?", "answer": "Nước Javel" },
          { "question": "Công thức hóa học của muối ăn hàng ngày chúng ta sử dụng là gì?", "answer": "\\(NaCl\\)" },
          { "question": "Chất khí nào phản ứng nổ mạnh với hydrogen ngay cả trong bóng tối và ở nhiệt độ cực thấp?", "answer": "Fluorine (\\(F_2\\))" },
          { "question": "Nguyên tố halogen nào được thêm vào muối ăn để phòng ngừa bệnh bướu cổ?", "answer": "Iodine (I)" },
          { "question": "Ứng dụng chính của nước chlorine hoặc clorua vôi trong đời sống là gì?", "answer": "Khử trùng nước sinh hoạt và tẩy trắng" }
        ]
      }
    ]
  },
  {
    grade: 11,
    subject: "Hóa Học 11",
    topics: [
      {
        id: "11_equilibrium",
        title: "Chương 1. Cân bằng hóa học",
        description: "Khái niệm về cân bằng hóa học, hằng số Kc, sự chuyển dịch cân bằng và cân bằng trong dung dịch nước (sự điện li, pH, chất chỉ thị).",
        iconName: "Compass",
        color: "#0369a1",
        data: [
          { "question": "Phản ứng xảy ra theo hai chiều ngược nhau trong cùng điều kiện gọi là phản ứng gì?", "answer": "Phản ứng thuận nghịch" },
          { "question": "Trạng thái của phản ứng khi tốc độ phản ứng thuận bằng tốc độ phản ứng nghịch gọi là gì?", "answer": "Cân bằng hóa học" },
          { "question": "Yếu tố nào làm tăng tốc độ phản ứng nhưng KHÔNG làm dịch chuyển cân bằng hóa học?", "answer": "Chất xúc tác" },
          { "question": "Sự phân li các chất thành các ion khi tan trong nước hoặc nóng chảy gọi là gì?", "answer": "Sự điện li" },
          { "question": "Theo thuyết Brønsted-Lowry, hợp chất có khả năng cho proton (\\(H^+\\)) được gọi là gì?", "answer": "Acid" },
          { "question": "Theo thuyết Brønsted-Lowry, hợp chất có khả năng nhận proton (\\(H^+\\)) được gọi là gì?", "answer": "Base" },
          { "question": "Đại lượng đặc trưng cho nồng độ ion hydro, dùng để đo tính acid/base của dung dịch là gì?", "answer": "pH" },
          { "question": "Một dung dịch có giá trị pH lớn hơn 7 ở nhiệt độ thường thì có môi trường gì?", "answer": "Môi trường base" },
          { "question": "Một dung dịch có giá trị pH nhỏ hơn 7 ở nhiệt độ thường thì có môi trường gì?", "answer": "Môi trường acid" },
          { "question": "Nước tinh khiết ở nhiệt độ chuẩn 25 độ C có giá trị pH bằng bao nhiêu?", "answer": "pH = 7" },
          { "question": "Hằng số cân bằng hóa học biểu thị tỉ lệ nồng độ sản phẩm và chất tham gia phản ứng ký hiệu là gì?", "answer": "\\(K_c\\)" },
          { "question": "Khi tăng nhiệt độ, cân bằng của phản ứng thu nhiệt (\\(\\Delta H > 0\\)) dịch chuyển theo chiều nào?", "answer": "Chiều thuận" },
          { "question": "Nguyên lý cho biết sự chuyển dịch cân bằng chống lại tác động bên ngoài gọi là gì?", "answer": "Nguyên lý Le Chatelier" },
          { "question": "Chất điện li phân li hoàn toàn thành các ion khi tan trong nước gọi là chất điện li gì?", "answer": "Chất điện li mạnh" },
          { "question": "Nước nguyên chất tự điện li rất yếu sinh ra hai ion nào có nồng độ bằng nhau?", "answer": "\\(H^+\\) và \\(OH^-\\)" },
          { "question": "Chất chỉ thị màu đổi sang màu hồng khi gặp dung dịch base mạnh có tên là gì?", "answer": "Phenolphthalein" },
          { "question": "Giấy quỳ tím khi gặp dung dịch có pH nhỏ hơn 5 sẽ chuyển sang màu gì?", "answer": "Màu đỏ" },
          { "question": "Chất điện li yếu là chất khi tan trong nước chỉ phân li thế nào?", "answer": "Phân li một phần" },
          { "question": "Phản ứng trung hòa giữa dung dịch acid và dung dịch base tạo ra muối và chất nào?", "answer": "Nước" },
          { "question": "Trị số tích số ion của nước (\\(K_w\\)) ở nhiệt độ chuẩn 25 độ C có giá trị bằng bao nhiêu?", "answer": "\\(10^{-14}\\)" }
        ]
      },
      {
        id: "11_nitrogen_sulfur",
        title: "Chương 2. Nitrogen - Sulfur",
        description: "Tính chất đơn chất nitrogen, sulfur, amoniac, các oxit của nitrogen, axit nitric, lưu huỳnh đioxit, axit sunfuric và muối sunfat.",
        iconName: "Sparkles",
        color: "#854d0e",
        data: [
          { "question": "Khí đơn chất nào chiếm khoảng 78% thể tích bầu khí quyển Trái Đất?", "answer": "Nitrogen" },
          { "question": "Trong tự nhiên, hiện tượng sấm sét tạo điều kiện cho khí nitơ phản ứng tạo loại phân bón nào?", "answer": "Phân đạm" },
          { "question": "Khí có mùi khai, tan cực tốt trong nước tạo thành dung dịch base yếu có công thức là gì?", "answer": "\\(NH_3\\)" },
          { "question": "Acid mạnh nào có tính oxi hóa cực mạnh, hòa tan được hầu hết kim loại trừ vàng và bạch kim?", "answer": "Nitric acid" },
          { "question": "Hiện tượng nước mưa có pH nhỏ hơn 5,6 do chứa axit sinh ra từ khí oxit nitơ và lưu huỳnh gọi là?", "answer": "Mưa acid" },
          { "question": "Đơn chất phi kim nào có màu vàng, giòn ở nhiệt độ thường và được dùng để sản xuất diêm?", "answer": "Sulfur" },
          { "question": "Khí độc có mùi hắc, gây ho, sinh ra do đốt than đá và là tác nhân chính gây mưa acid là khí gì?", "answer": "Sulfur dioxide" },
          { "question": "Acid sunfuric đặc có đặc tính nguy hiểm nào cực kỳ mạnh, dễ gây bỏng sâu khi tiếp xúc với da?", "answer": "Tính háo nước" },
          { "question": "Để pha loãng dung dịch acid sunfuric đặc một cách an toàn, ta phải làm thế nào?", "answer": "Rót từ từ acid vào nước" },
          { "question": "Thuốc thử đặc trưng dùng để nhận biết ion sunfat (\\(SO_4^{2-}\\)) trong dung dịch muối là gì?", "answer": "Dung dịch muối Barium" },
          { "question": "Muối amoni khi tác dụng với dung dịch kiềm nóng sinh ra chất khí có mùi khai là gì?", "answer": "Khí ammonia" },
          { "question": "Hợp chất nào của nitơ được dùng phổ biến để làm chất làm lạnh sâu bảo quản thực phẩm và tế bào?", "answer": "Nitrogen lỏng" },
          { "question": "Các loại muối nitrate (\\(NO_3^-\\)) có tính chất tan thế nào trong môi trường nước?", "answer": "Tất cả đều tan tốt" },
          { "question": "Trong công nghiệp, ammonia (\\(NH_3\\)) được tổng hợp trực tiếp từ \\(N_2\\) và \\(H_2\\) qua quá trình nào?", "answer": "Quá trình Haber-Bosch" },
          { "question": "Quặng pyrite sắt dùng làm nguyên liệu chính sản xuất sulfuric acid có công thức hóa học là gì?", "answer": "\\(FeS_2\\)" },
          { "question": "Khi cho lưu huỳnh tác dụng với kim loại kẽm (Zn) ở nhiệt độ cao, sản phẩm sinh ra là gì?", "answer": "Zinc sulfide" },
          { "question": "Hợp chất muối sunfat của calcium ngậm nước dùng để bó bột y tế khi gãy xương gọi là gì?", "answer": "Thạch cao" },
          { "question": "Trạng thái số oxi hóa cao nhất của nguyên tố sulfur (S) trong các hợp chất hóa học là?", "answer": "+6" },
          { "question": "Số oxi hóa thấp nhất của nguyên tố nitrogen (N) trong hợp chất amoniac (\\(NH_3\\)) là?", "answer": "-3" },
          { "question": "Chất khí cực độc có mùi trứng thối đặc trưng sinh ra khi phân hủy xác động thực vật là gì?", "answer": "Hydrogen sulfide" }
        ]
      },
      {
        id: "11_organic_intro",
        title: "Chương 3. Đại cương về hóa học hữu cơ",
        description: "Khái niệm hợp chất hữu cơ, phương pháp tách biệt tinh chế, công thức phân tử, cấu tạo hóa học và thuyết cấu tạo hóa học hữu cơ.",
        iconName: "Atom",
        color: "#15803d",
        data: [
          { "question": "Hợp chất hữu cơ nhất thiết phải chứa nguyên tố hóa học nào trong thành phần?", "answer": "Carbon" },
          { "question": "Liên kết hóa học chủ yếu xuất hiện trong phân tử các hợp chất hữu cơ là loại liên kết nào?", "answer": "Liên kết cộng hóa trị" },
          { "question": "Các hợp chất có cùng công thức phân tử nhưng khác nhau về cấu trúc hóa học gọi là gì?", "answer": "Đồng phân" },
          { "question": "Các chất có cấu tạo tương tự nhau nhưng thành phần phân tử hơn kém nhau một hay nhiều nhóm CH2 là?", "answer": "Đồng đẳng" },
          { "question": "Phương pháp tách biệt chất lỏng dựa trên sự khác nhau về nhiệt độ sôi của các chất gọi là gì?", "answer": "Phương pháp chưng cất" },
          { "question": "Phương pháp tách chất tan ra khỏi dung dịch bằng cách dùng một dung môi có độ hòa tan tốt hơn gọi là gì?", "answer": "Phương pháp chiết" },
          { "question": "Phương pháp làm tinh chế chất rắn dựa trên sự thay đổi độ tan của chất theo nhiệt độ gọi là gì?", "answer": "Phương pháp kết tinh" },
          { "question": "Phương pháp phân tách các chất trong hỗn hợp dựa trên ái lực khác nhau của chúng giữa pha tĩnh và pha động gọi là gì?", "answer": "Phương pháp sắc ký" },
          { "question": "Công thức biểu thị số lượng nguyên tử của mỗi nguyên tố thực tế trong một phân tử gọi là gì?", "answer": "Công thức phân tử" },
          { "question": "Công thức biểu thị tỷ lệ số nguyên tử tối giản nhất giữa các nguyên tố trong hợp chất gọi là gì?", "answer": "Công thức đơn giản nhất" },
          { "question": "Cách biểu diễn trật tự sắp xếp và liên kết của các nguyên tử trong phân tử hợp chất hữu cơ gọi là gì?", "answer": "Công thức cấu tạo" },
          { "question": "Mục đích của phân tích định tính nguyên tố trong hợp chất hữu cơ là xác định điều gì?", "answer": "Sự có mặt của các nguyên tố" },
          { "question": "Để nhận biết sự có mặt của carbon, người ta đốt cháy hợp chất hữu cơ rồi dẫn sản phẩm qua dung dịch nào?", "answer": "Nước vôi trong (dung dịch calcium hydroxide)" },
          { "question": "Sự vẩn đục trắng khi dẫn sản phẩm cháy có CO2 qua nước vôi trong là do chất nào tạo thành?", "answer": "\\(CaCO_3\\)" },
          { "question": "Để nhận biết sự có mặt của hydrogen, người ta chuyển hydrogen thành nước rồi dùng chất khan nào để hóa xanh?", "answer": "Copper(II) sulfate khan (\\(CuSO_4\\))" },
          { "question": "Đồng phân cấu tạo bao gồm các dạng đồng phân nào?", "answer": "Đồng phân mạch carbon, đồng phân nhóm chức và vị trí nhóm chức" },
          { "question": "Liên kết đơn duy nhất nối giữa hai nguyên tử trong hợp chất hữu cơ luôn là loại liên kết nào?", "answer": "Liên kết xích ma (sigma)" },
          { "question": "Một liên kết đôi C=C bao gồm những liên kết nhỏ nào?", "answer": "Một liên kết sigma và một liên kết pi (π)" },
          { "question": "Một liên kết ba C≡C bao gồm những liên kết nhỏ nào?", "answer": "Một liên kết sigma và hai liên kết pi (π)" },
          { "question": "Thuyết mô tả trật tự liên kết và ảnh hưởng qua lại của các nguyên tử trong phân tử hữu cơ gọi là gì?", "answer": "Thuyết cấu tạo hóa học" }
        ]
      },
      {
        id: "11_hydrocarbon",
        title: "Chương 4. Hydrocarbon",
        description: "Khám phá Alkane no, Hydrocarbon không no (Alkene, Alkyne) và Arene (Hydrocarbon thơm).",
        iconName: "Zap",
        color: "#4f46e5",
        data: [
          { "question": "Hydrocarbon mạch hở chỉ chứa liên kết đơn duy nhất trong phân tử được gọi là nhóm gì?", "answer": "Alkane" },
          { "question": "Alkane đơn giản nhất, là thành phần chính của khí thiên nhiên và khí bùn ao có công thức là gì?", "answer": "\\(CH_4\\)" },
          { "question": "Hydrocarbon mạch hở chứa một liên kết đôi C=C trong phân tử gọi là nhóm gì?", "answer": "Alkene" },
          { "question": "Alkene đơn giản nhất có công thức phân tử là gì?", "answer": "\\(C_2H_4\\)" },
          { "question": "Hydrocarbon mạch hở chứa một liên kết ba trong phân tử gọi là nhóm gì?", "answer": "Alkyne" },
          { "question": "Alkyne đơn giản nhất dùng làm nhiên liệu cho đèn xì hàn cắt kim loại có tên gọi là gì?", "answer": "Acetylene" },
          { "question": "Hydrocarbon thơm đơn giản nhất có công thức phân tử C6H6 có tên gọi là gì?", "answer": "Benzene" },
          { "question": "Công thức chung của dãy đồng đẳng Alkane mạch hở có dạng thế nào?", "answer": "\\(C_n H_{2n+2}\\)" },
          { "question": "Công thức chung của dãy đồng đẳng Alkene mạch hở có dạng thế nào?", "answer": "\\(C_n H_{2n}\\)" },
          { "question": "Phản ứng hóa học đặc trưng nhất của alkane với halogen khi chiếu sáng là loại phản ứng nào?", "answer": "Phản ứng thế" },
          { "question": "Phản ứng đặc trưng nhất của alkene và alkyne do chứa liên kết pi kém bền là phản ứng gì?", "answer": "Phản ứng cộng" },
          { "question": "Chất khí nào được ứng dụng trong nông nghiệp giúp kích thích hoa quả nhanh chín?", "answer": "Ethylene" },
          { "question": "Để nhận biết nhanh alkene hoặc alkyne, người ta dẫn khí qua dung dịch thuốc thử màu cam nào?", "answer": "Nước Bromine" },
          { "question": "Khi đốt cháy hoàn toàn bất kỳ một hydrocarbon nào, sản phẩm thu được gồm hai khí nào?", "answer": "\\(CO_2\\) và \\(H_2O\\)" },
          { "question": "Gốc hydrocarbon hóa trị I tạo thành khi bớt đi một nguyên tử H từ phân tử alkane gọi là gì?", "answer": "Gốc alkyl" },
          { "question": "Chất hydrocarbon chiếm phần lớn thể tích trong bình khí gas sử dụng trong gia đình là gì?", "answer": "Propane và Butane" },
          { "question": "Quy tắc định hướng sản phẩm chính khi cộng tác nhân bất đối xứng vào alkene bất đối xứng gọi là gì?", "answer": "Quy tắc Markovnikov" },
          { "question": "Tên gọi của arene có công thức phân tử \\(C_7H_8\\) là gì?", "answer": "Toluene (methylbenzene)" },
          { "question": "Phản ứng bẻ gãy các liên kết C-C của các alkane mạch dài bằng nhiệt độ và xúc tác gọi là gì?", "answer": "Phản ứng cracking" },
          { "question": "Khi dẫn khí acetylene qua dung dịch chứa ion bạc trong amoniac, xuất hiện kết tủa màu gì?", "answer": "Màu vàng nhạt (bạc acetylide)" }
        ]
      },
      {
        id: "11_derivatives",
        title: "Chương 5. Dẫn xuất halogen - Alcohol - Phenol",
        description: "Tìm hiểu nhóm thế dẫn xuất halogen, liên kết hydrogen của alcohol và tính axit yếu của phenol.",
        iconName: "Layers",
        color: "#be185d",
        data: [
          { "question": "Hợp chất thu được khi thay thế một hay nhiều nguyên tử hydrogen trong hydrocarbon bằng halogen là gì?", "answer": "Dẫn xuất halogen" },
          { "question": "Hợp chất hữu cơ chứa nhóm -OH liên kết trực tiếp với nguyên tử carbon no được gọi là gì?", "answer": "Alcohol" },
          { "question": "Alcohol phổ biến nhất có trong bia, rượu và được dùng làm chất sát khuẩn vết thương là gì?", "answer": "Ethanol" },
          { "question": "Alcohol đa chức chứa 3 nhóm -OH liên kết với 3 carbon, có vị ngọt và tính chất nhớt là gì?", "answer": "Glycerol" },
          { "question": "Hợp chất hữu cơ có nhóm -OH liên kết trực tiếp với nguyên tử carbon của vòng benzene gọi là gì?", "answer": "Phenol" },
          { "question": "Mặc dù phenol có tính acid yếu nhưng nó lại không thể làm đổi màu chất chỉ thị nào?", "answer": "Quỳ tím" },
          { "question": "Phenol phản ứng cực nhạy với nước bromine tạo ra kết tủa có màu gì?", "answer": "Màu trắng" },
          { "question": "Số lượng nhóm hydroxy (-OH) có trong một phân tử ethylene glycol là bao nhiêu?", "answer": "2 nhóm" },
          { "question": "Hợp chất alcohol nào cực độc, uống nhầm lượng nhỏ có thể gây mù lòa hoặc tử vong?", "answer": "Methanol" },
          { "question": "Phản ứng tách nước từ ethanol ở 170 độ C có xúc tác H2SO4 đặc sinh ra chất khí nào?", "answer": "Ethylene" },
          { "question": "Phenol có tính acid mạnh hơn hay yếu hơn so với ethanol?", "answer": "Mạnh hơn" },
          { "question": "Nhiệt độ sôi của alcohol cao hơn nhiều so với hydrocarbon cùng khối lượng phân tử là do yếu tố nào?", "answer": "Liên kết hydrogen liên phân tử" },
          { "question": "Alcohol bậc 1 khi bị oxi hóa không hoàn toàn bằng CuO đun nóng tạo thành hợp chất gì?", "answer": "Aldehyde" },
          { "question": "Alcohol bậc 2 khi bị oxi hóa không hoàn toàn bằng CuO đun nóng tạo thành hợp chất gì?", "answer": "Ketone" },
          { "question": "Quy tắc xác định hướng tách hydrogen halide ra khỏi dẫn xuất halogen để tạo sản phẩm chính là gì?", "answer": "Quy tắc Zaitsev" },
          { "question": "Khi cho dung dịch glycerol tác dụng với copper(II) hydroxide ở nhiệt độ thường, thu được dung dịch màu gì?", "answer": "Màu xanh lam thẫm" },
          { "question": "Khi cho phenol tác dụng với dung dịch sodium hydroxide, thu được sản phẩm muối tan là gì?", "answer": "Sodium phenolate" },
          { "question": "Nhóm hợp chất CFC từng làm chất lạnh trong tủ lạnh nhưng gây thủng tầng ozon thuộc loại nào?", "answer": "Dẫn xuất halogen" },
          { "question": "Khi cho dẫn xuất halogen tác dụng với dung dịch kiềm nóng trong nước, xảy ra phản ứng gì?", "answer": "Phản ứng thế nguyên tử halogen bằng nhóm -OH" },
          { "question": "Để nhận biết và phân biệt phenol với alcohol thơm, người ta có thể dùng thuốc thử nào đặc trưng nhất?", "answer": "Dung dịch nước Bromine hoặc dung dịch muối Fe(III)" }
        ]
      },
      {
        id: "11_carbonyl_carboxylic",
        title: "Chương 6. Hợp chất carbonyl - Carboxylic acid",
        description: "Cấu trúc nhóm chức carbonyl (aldehyde, ketone), tính chất hóa học đặc trưng và các carboxylic acid phổ biến.",
        iconName: "Flame",
        color: "#db2777",
        data: [
          { "question": "Hợp chất hữu cơ chứa nhóm chức -CHO liên kết với gốc hydrocarbon hoặc hydro gọi là gì?", "answer": "Aldehyde" },
          { "question": "Dung dịch formaldehyde trong nước có nồng độ từ 37 đến 40% thường gọi là gì?", "answer": "Formalin" },
          { "question": "Phản ứng đặc trưng dùng để nhận biết aldehyde bằng thuốc thử Tollens được gọi là gì?", "answer": "Phản ứng tráng bạc" },
          { "question": "Hợp chất hữu cơ chứa nhóm chức -COOH liên kết với nguyên tử carbon hoặc hydro gọi là gì?", "answer": "Carboxylic acid" },
          { "question": "Carboxylic acid đơn giản nhất, có trong nọc độc của kiến và ong gọi là gì?", "answer": "Formic acid" },
          { "question": "Dung dịch acetic acid có nồng độ từ 2 đến 5% thường được dùng làm gia vị thực phẩm gọi là gì?", "answer": "Giấm ăn" },
          { "question": "Aldehyde tác dụng với hydrogen dưới xúc tác nickel đun nóng sẽ bị khử tạo thành chất gì?", "answer": "Alcohol bậc 1" },
          { "question": "Carboxylic acid có tính acid mạnh hơn hay yếu hơn so với carbonic acid (\\(H_2CO_3\\))?", "answer": "Mạnh hơn" },
          { "question": "Tên gọi thông thường của hợp chất propan-2-one có chứa nhóm carbonyl là gì?", "answer": "Acetone" },
          { "question": "Khi cho carboxylic acid tác dụng với muối carbonate, phản ứng giải phóng chất khí gì?", "answer": "Khí carbon dioxide" },
          { "question": "Thuốc thử Tollens thực chất là dung dịch chứa phức chất của ion kim loại nào?", "answer": "Bạc (\\(Ag^+\\))" },
          { "question": "Khi cho aldehyde tác dụng với thuốc thử Fehling hoặc \\(Cu(OH)_2\\) trong kiềm nóng, xuất hiện kết tủa màu gì?", "answer": "Màu đỏ gạch (\\(Cu_2O\\))" },
          { "question": "Ketone có tham gia phản ứng tráng bạc hay làm mất màu nước bromine ở điều kiện thường không?", "answer": "Không" },
          { "question": "Hợp chất dicarboxylic acid đơn giản nhất có công thức hóa học là gì?", "answer": "\\((COOH)_2\\) (Oxalic acid)" },
          { "question": "Carboxylic acid có thể phản ứng với alcohol tạo este dưới sự xúc tác của acid mạnh đun nóng gọi là phản ứng gì?", "answer": "Phản ứng este hóa" },
          { "question": "Axit hữu cơ nào có mặt trong quả chanh, tạo nên vị chua thanh mát đặc trưng?", "answer": "Citric acid" },
          { "question": "Axit hữu cơ nào sinh ra trong quá trình lên men sữa chua tự nhiên?", "answer": "Lactic acid" },
          { "question": "Sản phẩm thu được khi cho benzoic acid tác dụng với dung dịch kiềm NaOH là muối gì?", "answer": "Sodium benzoate" },
          { "question": "Nhóm chức carbonyl đặc trưng bởi liên kết đôi nối giữa nguyên tử carbon và nguyên tử nào?", "answer": "Oxygen (C=O)" },
          { "question": "Aldehyde bị oxi hóa bởi dung dịch bromine tạo ra hợp chất thuộc loại nào?", "answer": "Carboxylic acid" }
        ]
      }
    ]
  },
  {
    grade: 12,
    subject: "Hóa Học 12",
    topics: [
      {
        id: "12_ester_lipid",
        title: "Chương 1: Ester - Lipid & Chất giặt rửa",
        description: "Học về hương liệu este, chất béo không no lỏng, no rắn, phản ứng xà phòng hóa và cơ chế xà phòng, tẩy rửa.",
        iconName: "Sparkles",
        color: "#b45309",
        data: [
          { "question": "Sản phẩm hữu cơ sinh ra khi đun nóng carboxylic acid với alcohol dưới xúc tác acid sunfuric là gì?", "answer": "Este" },
          { "question": "Công thức cấu tạo thu gọn của este đơn giản nhất ethyl acetate là gì?", "answer": "\\(CH_3COOC_2H_5\\)" },
          { "question": "Phản ứng thủy phân este trong môi trường kiềm còn được gọi là phản ứng gì?", "answer": "Phản ứng xà phòng hóa" },
          { "question": "Este có mùi thơm đặc trưng của chuối chín có tên gọi là gì?", "answer": "Isoamyl acetate" },
          { "question": "Chất béo (lipid) về mặt hóa học là triester của glycerol với chất nào?", "answer": "Các acid béo" },
          { "question": "Sản phẩm chung luôn thu được khi tiến hành thủy phân bất kỳ chất béo nào là gì?", "answer": "Glycerol" },
          { "question": "Axit béo no tiêu biểu có trong mỡ động vật có công thức \\(C_{17}H_{35}COOH\\) có tên là gì?", "answer": "Stearic acid" },
          { "question": "Axit béo không no tiêu biểu có trong dầu ô-liu có công thức \\(C_{17}H_{33}COOH\\) có tên là gì?", "answer": "Oleic acid" },
          { "question": "Chất béo lỏng chứa nhiều gốc acid béo không no thường có nguồn gốc chủ yếu từ đâu?", "answer": "Dầu thực vật" },
          { "question": "Phản ứng cộng hydrogen để chuyển hóa dầu thực vật lỏng thành mỡ rắn (bơ nhân tạo) gọi là gì?", "answer": "Phản ứng hydrogen hóa" },
          { "question": "Xà phòng thông thường là hỗn hợp muối sodium hoặc potassium của chất nào?", "answer": "Axit béo" },
          { "question": "Ưu điểm vượt trội của chất giặt rửa tổng hợp so với xà phòng thông thường là gì?", "answer": "Không tạo kết tủa trong nước cứng" },
          { "question": "Phần kị nước trong phân tử xà phòng hướng về phía nào khi làm sạch quần áo bẩn?", "answer": "Vết bẩn dầu mỡ" },
          { "question": "Chỉ số este hóa biểu thị lượng KOH cần thiết để trung hòa este trong bao nhiêu gam chất béo?", "answer": "1 gam" },
          { "question": "Khi thủy phân este trong môi trường acid, phản ứng xảy ra hoàn toàn hay thuận nghịch?", "answer": "Thuận nghịch" },
          { "question": "Este có nhiệt độ sôi thế nào so với alcohol và carboxylic acid có cùng khối lượng phân tử?", "answer": "Thấp hơn" },
          { "question": "Chất béo bị ôi thiu do liên kết đôi C=C của axit béo không no bị oxi hóa bởi không khí tạo thành chất gì?", "answer": "Aldehyde" },
          { "question": "Để sản xuất xà phòng trong công nghiệp, người ta đun chất béo với dung dịch kiềm nào phổ biến nhất?", "answer": "Dung dịch NaOH" },
          { "question": "Este của phenol khi thủy phân trong dung dịch NaOH dư sẽ sinh ra sản phẩm gồm hai muối và chất nào?", "answer": "Nước" },
          { "question": "Chất giặt rửa tổng hợp thường chứa muối gốc sulfonate hay carboxylate?", "answer": "Gốc sulfonate" }
        ]
      },
      {
        id: "12_carbohydrate",
        title: "Chương 2: Carbohydrate - Glucose & Polysaccharide",
        description: "Glucose tạp chức tráng bạc, saccharose disaccharide ngọt lịm, tinh bột xanh tím với iod và cấu trúc gỗ cellulose.",
        iconName: "Layers",
        color: "#4d7c0f",
        data: [
          { "question": "Hợp chất hữu cơ tạp chức có công thức chung là Cn(H2O)m được gọi là gì?", "answer": "Carbohydrate" },
          { "question": "Đơn chất monosaccharide tiêu biểu nhất, có nhiều trong quả nho chín và trong máu người là gì?", "answer": "Glucose" },
          { "question": "Đồng phân cấu tạo của glucose có vị ngọt sắc và chứa nhiều trong mật ong là gì?", "answer": "Fructose" },
          { "question": "Glucose và Fructose đều có chung công thức phân tử là gì?", "answer": "\\(C_6H_{12}O_6\\)" },
          { "question": "Glucose tác dụng với Cu(OH)2 ở nhiệt độ thường tạo ra dung dịch có màu sắc gì?", "answer": "Màu xanh lam" },
          { "question": "Loại đường disaccharide phổ biến nhất được sản xuất nhiều từ cây mía và củ cải đường là gì?", "answer": "Saccharose" },
          { "question": "Thủy phân hoàn toàn một phân tử saccharose thu được hỗn hợp gồm hai monosaccharide nào?", "answer": "Glucose và Fructose" },
          { "question": "Disaccharide là đồng phân của saccharose, có nhiều trong mạch nha và có phản ứng tráng bạc là gì?", "answer": "Maltose" },
          { "question": "Hợp chất carbohydrate dự trữ năng lượng chính trong các loại hạt, củ của thực vật là gì?", "answer": "Tinh bột" },
          { "question": "Tinh bột gồm hai dạng cấu trúc là amylose mạch thẳng và dạng mạch phân nhánh có tên là gì?", "answer": "Amylopectin" },
          { "question": "Thuốc thử vô cơ cực kỳ đặc trưng dùng để nhận biết sự hiện diện của tinh bột là gì?", "answer": "Dung dịch Iodine" },
          { "question": "Tinh bột tác dụng với dung dịch Iodine ở nhiệt độ thường sinh ra hợp chất màu gì?", "answer": "Màu xanh tím" },
          { "question": "Carbohydrate là thành phần cấu trúc chính tạo nên bộ khung vách tế bào gỗ thực vật là gì?", "answer": "Cellulose" },
          { "question": "Cellulose có cấu trúc mạch thẳng, không phân nhánh được tạo thành từ các mắt xích nào?", "answer": "Beta-glucose" },
          { "question": "Thủy phân hoàn toàn tinh bột hoặc cellulose đến cùng đều chỉ thu được sản phẩm duy nhất là gì?", "answer": "Glucose" },
          { "question": "Tơ nhân tạo visco và tơ axetat được sản xuất từ nguyên liệu polyme tự nhiên ban đầu là gì?", "answer": "Cellulose" },
          { "question": "Saccharose không tham gia phản ứng tráng bạc vì trong phân tử không chứa nhóm chức nào?", "answer": "Nhóm chức aldehyde" },
          { "question": "Khi lên men rượu glucose dưới tác dụng của enzyme ở nhiệt độ thích hợp, ta thu được khí gì?", "answer": "Khí carbon dioxide" },
          { "question": "Thuốc súng không khói là một este của cellulose với nitric acid có tên gọi là gì?", "answer": "Cellulose trinitrate" },
          { "question": "Glucose bị khử bằng hydrogen dưới tác dụng của nickel và nhiệt độ tạo thành chất ngọt nào?", "answer": "Sorbitol" }
        ]
      },
      {
        id: "12_amine_protein",
        title: "Chương 3: Hợp chất chứa Nitrogen",
        description: "Anilin kết tủa trắng, amino acid lưỡng tính, liên kết peptide, phản ứng màu biuret và enzym xúc tác sinh học.",
        iconName: "Atom",
        color: "#a21caf",
        data: [
          { "question": "Hợp chất hữu cơ thu được khi thay thế nguyên tử H trong phân tử NH3 bằng gốc hydrocarbon là?", "answer": "Amin" },
          { "question": "Amin thơm đơn giản nhất, ít tan trong nước, tác dụng nước bromine tạo kết tủa trắng là?", "answer": "Aniline" },
          { "question": "Hợp chất hữu cơ lưỡng tính đồng thời chứa nhóm amino (-NH2) và carboxyl (-COOH) gọi là gì?", "answer": "Amino acid" },
          { "question": "Amino acid đơn giản nhất, có khối lượng phân tử bằng 75 đvC là chất nào?", "answer": "Glycine" },
          { "question": "Liên kết hóa học đặc trưng nối giữa hai đơn vị alpha-amino acid trong chuỗi peptit gọi là gì?", "answer": "Liên kết peptide" },
          { "question": "Phản ứng màu đặc trưng của peptide (từ tripeptide trở lên) với Cu(OH)2/OH- gọi là phản ứng gì?", "answer": "Phản ứng màu biuret" },
          { "question": "Sự đông tụ lòng trắng trứng khi đun nóng ở nhiệt độ cao gọi là hiện tượng gì?", "answer": "Sự đông tụ protein" },
          { "question": "Amino acid có khả năng làm quỳ tím hóa xanh do chứa nhiều nhóm amino hơn nhóm carboxyl là gì?", "answer": "Lysine" },
          { "question": "Amino acid có khả năng làm quỳ tím hóa đỏ do chứa nhiều nhóm carboxyl hơn nhóm amino là gì?", "answer": "Glutamic acid" },
          { "question": "Số lượng liên kết peptide có trong một phân tử tetrapeptide mạch hở là bao nhiêu?", "answer": "3 liên kết" },
          { "question": "Hợp chất bột ngọt dùng làm gia vị thức ăn hàng ngày là muối mononatri của acid nào?", "answer": "Glutamic acid" },
          { "question": "Dung dịch methylamine (\\(CH_3NH_2\\)) có lực base thế nào so với ammonia (\\(NH_3\\))?", "answer": "Mạnh hơn" },
          { "question": "Để rửa sạch ống nghiệm dính aniline (không tan trong nước), ta nên tráng ống nghiệm bằng dung dịch nào trước?", "answer": "Dung dịch HCl" },
          { "question": "Ở trạng thái tinh thể, amino acid tồn tại dưới dạng ion nào làm chúng có nhiệt độ nóng chảy cao?", "answer": "Ion lưỡng cực" },
          { "question": "Các peptit và protein bị thủy phân hoàn toàn dưới tác dụng của acid, base hoặc chất xúc tác nào?", "answer": "Enzyme" },
          { "question": "Liên kết peptide được tạo thành do sự loại nước giữa nhóm carboxyl của axit này và nhóm nào của axit kia?", "answer": "Nhóm amino" },
          { "question": "Chất xúc tác sinh học có bản chất là protein, giúp tăng tốc độ các phản ứng sinh hóa gọi là gì?", "answer": "Enzyme" },
          { "question": "Phản ứng màu biuret tạo ra hợp chất có màu đặc trưng gì khi peptide tác dụng với copper(II) hydroxide?", "answer": "Màu tím" },
          { "question": "Protein phức tạp là protein có chứa thêm thành phần phi protein như nucleic acid hay chất nào?", "answer": "Lipid" },
          { "question": "Hợp chất amino acid đóng vai trò là khối xây dựng cơ bản (monomer) để tạo nên chuỗi protein là gì?", "answer": "Alpha-amino acid" }
        ]
      },
      {
        id: "12_polymer",
        title: "Chương 4: Polymer & Vật liệu Polymer",
        description: "Khái niệm trùng hợp, trùng ngưng, cao su lưu hóa đàn hồi cực tốt, tơ nilon dệt len bền dai.",
        iconName: "Sparkles",
        color: "#0284c7",
        data: [
          { "question": "Hợp chất có khối lượng phân tử rất lớn do nhiều đơn vị nhỏ gọi là mắt xích liên kết là gì?", "answer": "Polymer" },
          { "question": "Phản ứng kết hợp nhiều phân tử monomer giống nhau tạo polymer không giải phóng chất phụ là gì?", "answer": "Phản ứng trùng hợp" },
          { "question": "Phản ứng kết hợp các monomer đồng thời giải phóng các phân tử nhỏ (như nước) tạo polymer là gì?", "answer": "Phản ứng trùng ngưng" },
          { "question": "Polymer dùng làm màng bọc thực phẩm, được trùng hợp từ khí ethylene có tên viết tắt là gì?", "answer": "PE" },
          { "question": "Nhựa PVC được ứng dụng làm ống dẫn nước được tổng hợp trực tiếp từ monomer nào?", "answer": "Vinyl chloride" },
          { "question": "Polymer dùng để chế tạo thủy tinh hữu cơ plexiglas bền đẹp có tên viết tắt là gì?", "answer": "PMMA" },
          { "question": "Tơ nilon-6,6 cực bền thuộc loại tơ polyamide được tổng hợp bằng phản ứng hóa học nào?", "answer": "Phản ứng trùng ngưng" },
          { "question": "Tơ nitron (hay olon) dùng để dệt len ấm được tổng hợp bằng phản ứng trùng hợp monomer nào?", "answer": "Acrylonitrile" },
          { "question": "Cao su thiên nhiên khai thác từ mủ cây cao su có thành phần chính là polymer của chất nào?", "answer": "Isoprene" },
          { "question": "Quá trình lưu hóa cao su bằng cách đun nóng với chất nào để tạo cầu nối không gian giúp tăng tính đàn hồi?", "answer": "Lưu huỳnh" },
          { "question": "Vật liệu polyme có tính dẻo, được dùng để sản xuất các vật dụng hàng ngày gọi là gì?", "answer": "Chất dẻo" },
          { "question": "Chất dẻo teflon chịu nhiệt cực tốt dùng làm lớp chống dính chảo được tổng hợp từ chất nào?", "answer": "Tetrafluoroethylene" },
          { "question": "Polyme nào thuộc loại tơ tự nhiên được tiết ra từ con tằm?", "answer": "Tơ tằm" },
          { "question": "Loại tơ nhân tạo được điều chế bằng cách cho cellulose tác dụng với acetic anhydride là gì?", "answer": "Tơ acetate" },
          { "question": "Polyme dẻo dai làm áo mưa, giả da được tổng hợp từ vinyl clorua có tên đầy đủ là gì?", "answer": "Polyvinyl chloride" },
          { "question": "Nhựa phenol-formaldehyde được tổng hợp từ hai chất ban đầu là phenol và chất khí nào?", "answer": "Formaldehyde" },
          { "question": "Chất có cấu trúc mạng lưới không gian bền vững hơn nhựa nhiệt dẻo được gọi là gì?", "answer": "Nhựa nhiệt rắn" },
          { "question": "Cao su buna được tổng hợp bằng phản ứng trùng hợp chất nào dưới xúc tác sodium?", "answer": "Buta-1,3-diene" },
          { "question": "Chất dẻo hoặc cao su khi phân hủy sinh học rất khó khăn ngoài môi trường gây ra hiện tượng ô nhiễm gì?", "answer": "Rác thải nhựa" },
          { "question": "Polyme nào cấu tạo nên màng sơn dai bền, được sản xuất từ phản ứng ester hóa hoặc trùng hợp gọi là?", "answer": "Chất kết dính" }
        ]
      },
      {
        id: "12_electrochemistry",
        title: "Chương 5: Pin điện & Điện phân",
        description: "Học suất điện động chuẩn, cơ chế hoạt động pin Lithium-ion và phản ứng điện phân cực âm, cực dương.",
        iconName: "Zap",
        color: "#6d28d9",
        data: [
          { "question": "Đại lượng đo khả năng oxi hóa - khử của một cặp oxi hóa - khử ở điều kiện chuẩn gọi là gì?", "answer": "Thế điện cực chuẩn" },
          { "question": "Thiết bị biến đổi hóa năng của phản ứng oxi hóa - khử tự phát thành điện năng gọi là gì?", "answer": "Pin điện hóa" },
          { "question": "Trong pin điện hóa Daniel (Kẽm - Đồng), cực âm (anode) được làm bằng kim loại nào?", "answer": "Kẽm" },
          { "question": "Trong pin điện hóa, quá trình oxi hóa luôn xảy ra ở điện cực nào?", "answer": "Anode" },
          { "question": "Trong pin điện hóa, quá trình khử luôn xảy ra ở điện cực nào?", "answer": "Cathode" },
          { "question": "Pin điện hóa thế hệ mới nhẹ, hiệu điện thế cao, sạc lại được dùng cho điện thoại và xe điện là gì?", "answer": "Pin Lithium-ion" },
          { "question": "Quá trình phân hủy chất điện li dưới tác dụng của dòng điện một chiều chạy qua dung dịch gọi là?", "answer": "Điện phân" },
          { "question": "Khi điện phân dung dịch NaCl có màng ngăn, ở cathode thu được khí gì giải phóng?", "answer": "Khí hydrogen" },
          { "question": "Khi điện phân dung dịch NaCl có màng ngăn, ở anode thu được khí có màu vàng lục là khí gì?", "answer": "Khí chlorine" },
          { "question": "Trong quá trình điện phân dung dịch CuSO4, ở anode xảy ra sự oxi hóa chất nào nếu điện cực trơ?", "answer": "Nước" },
          { "question": "Phương pháp mạ một lớp kim loại bảo vệ bền đẹp lên vật bằng cách dùng vật đó làm cathode gọi là gì?", "answer": "Mạ điện" },
          { "question": "Khi điện phân nóng chảy Al2O3 để sản xuất nhôm, người ta thêm chất nào để giảm nhiệt độ nóng chảy?", "answer": "Criolit" },
          { "question": "Thế điện cực chuẩn của cặp oxi hóa - khử nào được chọn làm mốc bằng 0,00 V?", "answer": "Cặp hydrogen" },
          { "question": "Thiết bị dùng để đo suất điện động của pin điện hóa gọi là gì?", "answer": "Vôn kế" },
          { "question": "Sức điện động chuẩn của pin điện hóa bằng thế điện cực chuẩn của cực dương trừ thế điện cực chuẩn của cực nào?", "answer": "Cực âm" },
          { "question": "Pin chì-axit thường dùng làm nguồn khởi động trong xe máy, ô tô có tên gọi thông thường là gì?", "answer": "Acquy" },
          { "question": "Trong pin nhiên liệu, người ta cho khí hydrogen phản ứng trực tiếp với chất khí nào để tạo ra dòng điện?", "answer": "Khí oxygen" },
          { "question": "Sự khác biệt chính giữa điện phân và pin điện hóa là điện phân cần cung cấp yếu tố nào từ bên ngoài?", "answer": "Dòng điện một chiều" },
          { "question": "Khi điện phân dung dịch muối copper(II) sulfate với anode bằng đồng, hiện tượng đặc biệt xảy ra là gì?", "answer": "Anode tan" },
          { "question": "Định luật vật lý giúp tính toán khối lượng chất giải phóng ở điện cực khi điện phân là định luật nào?", "answer": "Định luật Faraday" }
        ]
      },
      {
        id: "12_metal_intro",
        title: "Chương 6: Đại cương về kim loại",
        description: "Học liên kết mạng tinh thể, dẻo dẫn điện nhiệt, hợp kim gang thép và hiện tượng ăn mòn điện hóa.",
        iconName: "Compass",
        color: "#0f766e",
        data: [
          { "question": "Các tính chất vật lý chung của kim loại gây ra chủ yếu bởi hạt vi mô nào tự do trong tinh thể?", "answer": "Các electron tự do" },
          { "question": "Kim loại dẻo nhất, có thể dát mỏng đến mức ánh sáng đi xuyên qua được và dùng làm trang sức là gì?", "answer": "Vàng" },
          { "question": "Kim loại có tính dẫn điện và dẫn nhiệt tốt nhất trong tất cả các kim loại là kim loại nào?", "answer": "Bạc" },
          { "question": "Kim loại có nhiệt độ nóng chảy cao nhất (3422 độ C), dùng làm dây tóc bóng đèn sợi đốt là gì?", "answer": "Wolfram" },
          { "question": "Kim loại duy nhất ở trạng thái lỏng ở điều kiện thường, được ứng dụng làm nhiệt kế đo sốt là gì?", "answer": "Thủy ngân" },
          { "question": "Kim loại cứng nhất trong tất cả các kim loại, có thể dùng để cắt kính và rạch thép là gì?", "answer": "Chromium" },
          { "question": "Tính chất hóa học đặc trưng và bao trùm nhất của tất cả các kim loại là tính chất gì?", "answer": "Tính khử" },
          { "question": "Dãy sắp xếp các kim loại theo mức độ hoạt động hóa học giảm dần từ trái sang phải gọi là gì?", "answer": "Dãy điện hóa" },
          { "question": "Vật liệu kim loại chứa hai hay nhiều nguyên tố hóa học nóng chảy trộn lẫn nhau gọi là gì?", "answer": "Hợp kim" },
          { "question": "Thép là hợp kim của sắt với carbon, trong đó hàm lượng carbon chiếm dưới bao nhiêu phần trăm?", "answer": "2%" },
          { "question": "Gang là hợp kim của sắt với carbon, trong đó hàm lượng carbon chiếm từ bao nhiêu phần trăm?", "answer": "2% đến 5%" },
          { "question": "Sự phá hủy kim loại hoặc hợp kim do tác dụng hóa học hoặc điện hóa của môi trường xung quanh là?", "answer": "Ăn mòn kim loại" },
          { "question": "Loại ăn mòn xảy ra khi có hai điện cực kim loại tiếp xúc trực tiếp trong dung dịch điện li gọi là gì?", "answer": "Ăn mòn điện hóa học" },
          { "question": "Để bảo vệ vỏ tàu biển bằng thép khỏi bị ăn mòn điện hóa, người ta thường gắn các tấm kim loại nào?", "answer": "Kẽm" },
          { "question": "Phương pháp bảo vệ kim loại bằng cách phủ lên bề mặt một lớp sơn, mỡ, chất dẻo gọi là phương pháp gì?", "answer": "Bảo vệ bề mặt" },
          { "question": "Kim loại nào bị thụ động hóa trong dung dịch HNO3 đặc nguội và H2SO4 đặc nguội?", "answer": "Sắt, Nhôm và Chromium" },
          { "question": "Ở nhiệt độ thường, kim loại sắt (Fe) có phản ứng thế được với dung dịch muối của kim loại nào?", "answer": "Đồng" },
          { "question": "Phản ứng nhiệt nhôm dùng để hàn đường ray tàu hỏa là phản ứng giữa bột nhôm và oxide của kim loại nào?", "answer": "Iron oxide" },
          { "question": "Kim loại kiềm được bảo quản bằng cách ngâm chìm hoàn toàn trong chất lỏng nào để tránh ẩm?", "answer": "Dầu hỏa" },
          { "question": "Phương pháp chủ yếu dùng để điều chế các kim loại hoạt động cực mạnh như Na, Ca, Al là phương pháp gì?", "answer": "Điện phân nóng chảy" }
        ]
      },
      {
        id: "12_group_ia_iia",
        title: "Chương 7: Nguyên tố nhóm IA và nhóm IIA",
        description: "Học phản ứng cháy sodium, vôi sống CaO, nước cứng chứa ion calcium magnesium và thạch cao CaSO4.",
        iconName: "Layers",
        color: "#be185d",
        data: [
          { "question": "Các nguyên tố nhóm IA trong bảng tuần hoàn (trừ hydrogen) có tên gọi chung là gì?", "answer": "Kim loại kiềm" },
          { "question": "Cấu hình electron lớp ngoài cùng chung của các nguyên tử kim loại kiềm là gì?", "answer": "ns^1" },
          { "question": "Kim loại nhẹ nhất trong bảng tuần hoàn, dùng chế tạo pin Lithium-ion cho điện thoại, xe điện là?", "answer": "Lithium" },
          { "question": "Kim loại kiềm nào phản ứng cực kỳ mãnh liệt với nước tạo dung dịch kiềm và tự bùng cháy?", "answer": "Sodium" },
          { "question": "Muối ăn hàng ngày dùng làm gia vị có công thức hóa học là gì?", "answer": "NaCl" },
          { "question": "Hợp chất kiềm xút ăn da dùng nhiều trong sản xuất xà phòng và giấy có công thức là gì?", "answer": "NaOH" },
          { "question": "Muối sodium hydrogencarbonat dùng làm bột nở trong làm bánh và thuốc dạ dày có công thức là gì?", "answer": "\\(NaHCO_3\\)" },
          { "question": "Các nguyên tố nhóm IIA trong bảng tuần hoàn được gọi chung là gì?", "answer": "Kim loại kiềm thổ" },
          { "question": "Cấu hình electron lớp ngoài cùng chung của các nguyên tử kim loại kiềm thổ là gì?", "answer": "ns^2" },
          { "question": "Kim loại kiềm thổ phổ biến nhất, đóng vai trò quan trọng trong cấu trúc xương và răng là gì?", "answer": "Calcium" },
          { "question": "Chất khí thoát ra khi cho các kim loại kiềm hoặc kiềm thổ tác dụng với nước là khí gì?", "answer": "Khí hydrogen" },
          { "question": "Hợp chất vôi sống dùng trong xây dựng và nông nghiệp có công thức hóa học là gì?", "answer": "CaO" },
          { "question": "Hợp chất calcium hydroxide dùng làm nước vôi trong có công thức hóa học là gì?", "answer": "\\(Ca(OH)_2\\)" },
          { "question": "Đá vôi, vỏ sò, thạch nhũ trong hang động có thành phần hóa học chính là muối nào?", "answer": "\\(CaCO_3\\)" },
          { "question": "Nước chứa hàm lượng cao các ion calcium (\\(Ca^{2+}\\)) và magnesium (\\(Mg^{2+}\\)) gọi là gì?", "answer": "Nước cứng" },
          { "question": "Phương pháp đun sôi hoặc dùng soda (\\(Na_2CO_3\\)) giúp loại bỏ độ cứng của loại nước nào?", "answer": "Nước cứng" },
          { "question": "Để nhận biết sự có mặt của ion calcium trong dung dịch, người ta dùng muối chứa ion nào tạo kết tủa trắng?", "answer": "Ion carbonate" },
          { "question": "Khoáng vật thạch cao nung dùng để đúc tượng và bó bột y tế có công thức hóa học là gì?", "answer": "\\(CaSO_4 . H_2O\\)" },
          { "question": "Khi thổi khí CO2 từ từ vào dung dịch nước vôi trong dư, hiện tượng quan sát được đầu tiên là gì?", "answer": "Vẩn đục trắng" },
          { "question": "Kim loại kiềm thổ nào nhẹ, bền, dùng chế tạo hợp kim siêu nhẹ làm vỏ máy bay và tên lửa?", "answer": "Beryllium" }
        ]
      },
      {
        id: "12_transition_complex",
        title: "Chương 8: Kim loại chuyển tiếp & Phức chất",
        description: "Học tính chất Fe, Cu, Cr hóa trị phong phú, liên kết phối trí trong cấu trúc phức chất đặc sắc.",
        iconName: "Atom",
        color: "#0369a1",
        data: [
          { "question": "Các nguyên tố thuộc nhóm B trong bảng tuần hoàn có tên gọi chung là gì?", "answer": "Kim loại chuyển tiếp" },
          { "question": "Kim loại chuyển tiếp phổ biến nhất trong đời sống, là thành phần chính của gang và thép là gì?", "answer": "Sắt" },
          { "question": "Trạng thái số oxi hóa phổ biến và bền nhất của sắt trong các hợp chất hóa học thường gặp là gì?", "answer": "+2 và +3" },
          { "question": "Kim loại dẻo màu đỏ, dẫn điện tốt thứ hai sau bạc, được dùng làm dây dẫn điện là gì?", "answer": "Đồng" },
          { "question": "Kim loại chuyển tiếp dùng để mạ bảo vệ chống gỉ cho thép và tạo màu cho kính là gì?", "answer": "Chromium" },
          { "question": "Hợp chất hóa học được tạo thành từ một ion kim loại trung tâm liên kết với các phối tử xung quanh là gì?", "answer": "Phức chất" },
          { "question": "Ion hoặc nguyên tử đóng vai trò hút các phối tử để tạo thành phức chất được gọi là gì?", "answer": "Ion trung tâm" },
          { "question": "Các phân tử hoặc ion mang cặp electron tự do liên kết trực tiếp với ion kim loại trung tâm gọi là gì?", "answer": "Phối tử" },
          { "question": "Số lượng liên kết phối trí tối đa mà ion trung tâm tạo được với các phối tử gọi là gì?", "answer": "Số phối trí" },
          { "question": "Phức chất của đồng với ammonia có màu xanh lam rất đặc trưng có công thức hóa học là gì?", "answer": "\\([Cu(NH_3)_4]^{2+}\\)" },
          { "question": "Thuốc thử Tollens dùng trong phản ứng tráng bạc của aldehyde có chứa ion phức chất của kim loại nào?", "answer": "Bạc" },
          { "question": "Hợp chất sinh học hemoglobin trong máu giúp vận chuyển khí oxygen có chứa phức chất của kim loại nào?", "answer": "Sắt" },
          { "question": "Chất diệp lục của cây xanh hấp thụ ánh sáng để quang hợp có chứa phức chất của kim loại nào?", "answer": "Magnesium" },
          { "question": "Loại liên kết hóa học đặc trưng hình thành giữa ion trung tâm và các phối tử trong phức chất là gì?", "answer": "Liên kết phối trí" },
          { "question": "Khi cho dung dịch NH3 dư vào dung dịch CuSO4, hiện tượng tạo kết tủa xanh sau đó kết tủa tan tạo dung dịch màu gì?", "answer": "Màu xanh lam đậm" },
          { "question": "Hợp chất phức chất bền vững của sắt với ion cyanide có màu xanh phổ rất đẹp có tên là gì?", "answer": "Prussian blue" },
          { "question": "Phức chất tan trong nước có chứa phối tử là các phân tử nước xung quanh ion kim loại gọi là gì?", "answer": "Phức chất aqua" },
          { "question": "Các phối tử thông thường như \\(H_2O\\), \\(NH_3\\), \\(Cl^-\\), \\(OH^-\\), phối tử nào có tính base mạnh nhất?", "answer": "\\(OH^-\\)" },
          { "question": "Phức chất có cấu trúc không gian hình học phẳng vuông thường gặp ở ion kim loại trung tâm nào?", "answer": "Pt^{2+}" },
          { "question": "Chất hữu cơ EDTA dùng để làm mềm nước cứng và giải độc kim loại thuộc loại chất tạo phức dạng nào?", "answer": "Chất tạo phức vòng càng" }
        ]
      }
    ]
  }
];
